spring:
  application:
    name: db-to-file-batch-processing
  flyway:
    baseline-on-migrate: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 25
      idle-timeout: 600000
      connection-test-query: SELECT 1 # Keep the connection alive if idle for a long time (needed in production)
      auto-commit: false
    url: "jdbc:mariadb://127.0.0.1:23306/batch-db-file?createDatabaseIfNotExist=true&useSSL=false&characterEncoding=UTF-8
    &allowPublicKeyRetrieval=true&useUnicode=yes&characterEncoding=UTF-8
    &useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC+3"
    username: user
    password: secret
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  threads:
    virtual:
      enabled: true
server:
  port: 9080
